name: Gerar Executável Windows

on:
  push:
    branches: [ main ]  # Executa toda vez que você der push na branch main

jobs:
  build:
    runs-on: windows-latest  # Aqui está o segredo: ele usa um Windows real

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller waitress

    - name: Gerar .EXE com PyInstaller
      run: |
        python -m PyInstaller --noconfirm --onefile --windowed --add-data "templates;templates" --add-data "static;static" --name "Meta_System_Cagece" app.py

    - name: Upload do Executável
      uses: actions/upload-artifact@v3
      with:
        name: Meta_System_Windows
        path: dist/Meta_System_Cagece.exe