name: Gerar Executavel MetaSystem

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job_build:
    runs-on: windows-latest  # Essencial para gerar .exe
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Gerar EXE com PyInstaller
        run: |
          # --onefile: Tudo num arquivo só
          # --noconsole: Não abre a janelinha preta do CMD ao iniciar
          # --add-data: Se tiver pastas de 'templates' ou 'static', inclua aqui
          pyinstaller --onefile --noconsole --name "MetaSystem_v1" app.py

      - name: Disponibilizar para Download (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: MetaSystem-Windows-Package
          path: dist/MetaSystem_v1.exe