name: Gerar Executavel MetaSystem

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job_build:
    runs-on: windows-latest  # CRÍTICO: Precisa ser Windows para gerar .exe
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Criar Executavel
        run: |
          # mude 'app.py' para o nome do seu arquivo principal se for diferente
          pyinstaller --onefile --noconsole --name "MetaSystem_Cagece" app.py

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: MetaSystem-Download-Test
          path: dist/MetaSystem_Cagece.exe